# ── старт симуляции ───────────────────────────────────────────────────────────
start_date: 2020-01-06 00:00:00   # понедельник — удобно для спринтов
horizon_days: 1825                # ≈ 5 лет
tick_minutes: 60                  # 1 SimPy-тик = 1 час

# ── команда ───────────────────────────────────────────────────────────────────
team:
  n_devs: 6                       # разработчиков в scrum-команде
  wip_limit: 10                   # максимальное WIP между In Progress ←→ Review

# ── поток задач от менеджеров ────────────────────────────────────────────────
arrival:
  lambda0: 3.0                    # ср. SP в день на 1 dev в «спокойное» время
  tau: 14                         # окно видимости дедлайна (дней)
  amplitude_quarter_end: 2.0      # во сколько раз растёт поток к концу квартала
  holiday_drop: 0.8               # ↓80 % задач в гос. праздник
  delta_qtr:                      # ступеньки нагрузки внутри квартала
    normal: 0.0                   # первые ~7 недель
    rush:   0.5                   # предпоследняя
    crunch: 1.0                   # последняя (hell-week)

# ── дефолтные параметры сотрудника ───────────────────────────────────────────
developer_defaults:
  s0: 2.5                         # базовая скорость без усталости, SP/день
  delta: 0.018                    # кривая «усталость → скорость»
  alpha: 0.04                     # скорость накопления усталости
  beta_weekday: 0.06              # скорость восстановления в будни
  beta_holiday: 0.09              # ускоренное восстановление в праздники
  w_thr: 4                        # «комфортный» дневной объём, SP
  tp0: 10                         # стартовая усталость
  kappa: 10                       # крутизна сигмоиды burnout-риска (если нужно)
  theta_recover: 0.4              # порог tp, ниже которого dev выходит из burnout
  lognorm_sigma: 0.25             # разброс дневной продуктивности (CV≈25 %)

# ── распределение story-points ───────────────────────────────────────────────
story_points:
  zipf_gamma: 1.0
